# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>

development:
  <<: *default
  database: sistema_chamados_rails_development

test:
  <<: *default
  database: sistema_chamados_rails_test

production:
  primary:
    <<: *default
    database: sistema_chamados_rails_production
  cache:
    <<: *default
    database: sistema_chamados_rails_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sistema_chamados_rails_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sistema_chamados_rails_production
    migrations_paths: db/cable_migrate
